### ISSUE TITLE
VSTS CI Build of Angular

### ISSUE THREAD

**Issue by spottedmahn** [spottedmahn/my-blog#7]
Followed this blog post: [Deploying an Angular CLI project using VSTS Build and Release](https://sethreid.co.nz/deploying-angular-cli-project-using-vsts-build-release/)

But I had specify the folder to package.json this to get it working on each NPM step:

![image](https://user-images.githubusercontent.com/14079228/40588743-6aaee21c-61b0-11e8-8843-2f0c15a3ff64.png)

Same for the zip source:

![image](https://user-images.githubusercontent.com/14079228/40588751-8f0d2fa6-61b0-11e8-8c4b-8031afdecaf4.png)

[First successful build](https://spottedmahn.visualstudio.com/Golf/_build/index?buildId=9&_a=summary)

![image](https://user-images.githubusercontent.com/14079228/40588735-4929c774-61b0-11e8-851f-1b619250b449.png)

[My Golf-CI Builds](https://spottedmahn.visualstudio.com/Golf/_build/index?context=mine&path=%5C&definitionId=1&_a=completed)

**Comment by spottedmahn** [comment]
Hi @sethreidnz - thanks 🙏 for your blog post!

**Comment by sethreidnz** [comment]
Is there an edit required for my tutorial or what you said above just to do with this repo?

**Comment by spottedmahn** [comment]
>Is there an edit required for my tutorial

I thought there was but now I'm not sure.  It was probably something I did differently.  Still pondering... 🤔
