### ISSUE TITLE
web.config in my CI/CD Angular App

### ISSUE THREAD

**Issue by spottedmahn** [spottedmahn/my-blog#8]
I've been following this great tutorial: [Deploying an Angular CLI project using VSTS Build and Release](https://sethreid.co.nz/deploying-angular-cli-project-using-vsts-build-release/) but I can't seem to get my web.config to deploy.

![image](https://user-images.githubusercontent.com/14079228/40623880-40c17024-6277-11e8-932a-63bad084ef0d.png)

![image](https://user-images.githubusercontent.com/14079228/40623885-464edc5c-6277-11e8-890d-74780eec50c5.png)

![image](https://user-images.githubusercontent.com/14079228/40623896-55e0fdc6-6277-11e8-834d-22deef3b6898.png)

---

I've tried putting it in two places in my app but it is not getting deployed.

![image](https://user-images.githubusercontent.com/14079228/40623910-8272647e-6277-11e8-8e55-335401c71328.png)

![image](https://user-images.githubusercontent.com/14079228/40623912-87a28cf8-6277-11e8-90bf-ada34779ea95.png)

I didn't expect it to work b/c we're zipping up the dist folder which won't have that file.

What am I missing? 🤔

---

Source code: https://github.com/spottedmahn/golf

[VSTS Public Project for CI/CD](https://spottedmahn.visualstudio.com/Golf/_releases2?definitionId=1&view=mine&_a=releases)

**Comment by spottedmahn** [comment]
Hi @sethreidnz - any thoughts?  How did you get web.config to deploy?  Thanks 🙏

**Comment by sethreidnz** [comment]
Are you doing a dotnet publish on your folder? It should get copied to your publish output as a result of that. And then you deploy your publish package. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore2x

**Comment by spottedmahn** [comment]
>Are you doing a dotnet publish on your folder?

Nope, I only have the Angular app at this point.

🤔

**Comment by sethreidnz** [comment]
Sorry I got confused I have a few of those tutorials. You need to copy over the file manually as part of your build. How I have done it before is that I would just use a npm package that can copy the file over into the dist folder like `copyfiles` and then you can just put a postbuild in your scripts section in package.json to copy that file over.

https://www.npmjs.com/package/postbuild

**Comment by spottedmahn** [comment]
>Sorry I got confused I have a few of those tutorials

No worries.  I really appreciate you taking the time to help me out!

>You need to copy over the file manually as part of your build

That makes sense.  I'll have to investigate that further, thanks! 🙏
